---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceSplitter
metadata:
  name: api
spec:
  splits:
    - weight: 100
      service: api
      serviceSubset: v1
    - weight: 0
      service: api
      serviceSubset: v2
