{
 "title": "Canary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Web Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_total{consul_source_service=\"web\", envoy_http_conn_manager_prefix=\"upstream\"}[30s])"
    }
   ]
  },
  {
   "title": "API V1 Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_total{consul_source_service=\"api\", envoy_http_conn_manager_prefix=\"public_listener\",pod=~\"api-deployment-v1-.*\"}[30s])"
    }
   ]
  },
  {
   "title": "API V2 Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_http_downstream_rq_total{consul_source_service=\"api\", envoy_http_conn_manager_prefix=\"public_listener\",pod=~\"api-deployment-v2-.*\"}[30s])"
    }
   ]
  }
 ]
}