---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: api
  namespace: default
spec:
  provider: linkerd
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # ClusterIP port number
    port: 9090
    # container port number or name (optional)
    targetPort: 9090
  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # Linkerd Prometheus checks
    metrics:
    - name: "consul-requests"
      templateRef:
        name: consul-requests
        # namespace is optional
        # when not specified, the canary namespace will be used
        namespace: default
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
      interval: 1m

---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: consul-requests
  namespace: default
spec:
  provider:
    type: prometheus
    address: http://prometheus-stack-kube-prom-prometheus.default.svc:9090
  query: |
    sum(
      rate(
        envoy_cluster_upstream_rq{
          namespace="{{ namespace }}",
          pod=~"{{ target }}-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)",
          envoy_cluster_name="local_app",
          envoy_response_code!~"5.*"
        }[{{ interval }}]
      )
    )
    /
    sum(
      rate(
        envoy_cluster_upstream_rq{
          namespace="{{ namespace }}",
          envoy_cluster_name="local_app",
          pod=~"{{ target }}-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)"
        }[{{ interval }}]
      )
    )
    * 100

---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: consul-duration
  namespace: default
spec:
  provider:
    type: prometheus
    address: http://prometheus-stack-kube-prom-prometheus.default.svc:9090
  query: |
    histogram_quantile(
      0.99,
      sum(
        rate(
          envoy_cluster_upstream_rq_time_bucket{
            namespace="{{ namespace }}",
            envoy_cluster_name="local_app",
            pod=~"{{ target }}-[0-9a-zA-Z]+(-[0-9a-zA-Z]+)"
          }[{{ interval }}]
        )
      ) by (le)
    )
