#apiVersion: split.smi-spec.io/v1alpha1
#kind: TrafficSplit
#metadata:
#  name: api-split
#spec:
#  # The root service that clients use to connect to the destination application.
#  service: api
#  # Services inside the namespace with their own selectors, endpoints and configuration.
#  backends:
#  - service: v1
#    weight: 9000m
#  - service: v2
#    weight: 1000m
---
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: api
  namespace: default
spec:
  provider: linkerd
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment-v1
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  service:
    # ClusterIP port number
    port: 9090
    # container port number or name (optional)
    targetPort: 9090
  analysis:
    # schedule interval (default 60s)
    interval: 30s
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 5
    # Linkerd Prometheus checks
    metrics:
    - name: request-success-rate
      # minimum req success rate (non 5xx responses)
      # percentage (0-100)
      thresholdRange:
        min: 99
      interval: 1m
