datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-stack-kube-prom-prometheus:9090
      isDefault: true
    
    - name: Loki
      type: loki
      url: http://loki:3100
      isDefault: false

admin:
  existingSecret: "grafana-password"
